name: Run Android Tests

on:
  pull_request:
    paths:
      - src/**

jobs:
  test:
    name: Run Android Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Setup 
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Create local.properties
        run:  |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties 
          echo "MAPS_API_KEY=YOUR_MAP_API_KEY_HERE" >> local.properties
          cat local.properties
        working-directory: src

      - name: Run test
        run: ./gradlew test
        working-directory: src

# TODO: Add instrumented tests
